version: '3'

services:
        db:
                container_name: ps-mysql
                image: mysql:5.7
                volumes:
                        - $PWD/data:/var/lib/mysql
                env_file:
                        - mysql.env
                ports:
                        - 3306:3306
                networks:
                        - ps-net
        ps:
                container_name: ps-web
                image: prestashop/prestashop
                volumes:
                        - $PWD/html:/var/www/html
                depends_on:
                        - db
                ports:
                        - 80:80
                env_file:
                        - ps.env
                networks:
                        - ps-net
networks:
        ps-net:
