version: '3'

services:
        db:
                container_name: wp-mysql
                image: mysql:5.7
                volumes:
                        - $PWD/mysql:/var/lib/mysql
                env_file: 
                        - db.env
                ports:
                        - 3306:3306
                networks:
                        - wp-net
        wp:
                container_name: wordpress
                depends_on:
                        - db
                image: wordpress:latest
                volumes:
                        - $PWD/html:/var/www/html
                ports:
                        - 80:80
                env_file:
                        - wp.env
                networks:
                        - wp-net

networks:
        wp-net:
                driver: bridge
