version: '3'
services:
        db:
                container_name: mysql
                image: mysql:5.7
                volumes:
                        - $PWD/data:/var/lib/mysql
                env_file:
                        - mysql.env
        web:
                container_name: joomla
                image: joomla
                volumes:
                        - $PWD/html:/var/www/html
                depends_on:
                        - db
                ports:
                        - 80:80
                env_file:
                        - joomla.env

